version: "3.5"
networks:
  api_wiremock:
    name: 'api_wiremock'
  mcf:
    name: "mcf"
    external: true
services:
  api_wiremock:
    build:
      context: './mocks/msf'
      dockerfile: './Dockerfile'
    entrypoint:
      - "java"
      - "-jar"
      - "/app/wiremock.jar"
      - "--port"
      - "8080"
      - "--proxy-all=http://api_wiremock_proxy:8888"
      - "--print-all-network-traffic"
    networks:
    - api_wiremock
    - mcf
    ports:
    - 8080:8080
    user: "10000"
    volumes:
    - "./mocks/msf/.data/mappings:/app/mappings"
    - "./mocks/msf/.data/__files:/app/__files"
  api_wiremock_proxy:
    build:
      context: './'
      dockerfile: './Dockerfile'
    entrypoint: ["./api-wiremock"]
    environment:
      API_WIREMOCK: http://api_wiremock:8080
      API_TARGET: REFER_TO_CONFIG.YAML
      PROXY_URL: REFER_TO_CONFIG.YAML
      Environment: production
    networks:
      - api_wiremock
    ports:
      - 8888:8888
    depends_on:
      - api_wiremock

